# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: echo $(Build.DefinitionName)_$(Build.DefinitionVersion)_$(Build.BuildId)_$(Build.BuildNumber) $(Build.SourceBranch) $(Build.Reason)
  displayName: 'build variables script'

- script: "$(Agent.BuildDirectory) $(Agent.TempDirectory)"
  displayName: 'agent variables script'
